# Tell Travis you want a Python environment to test in
language: python
# List the versions of Python you'd like to test against
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
install:
 - pip install -r requirements.txt
script:
 - pep8 app.py
 - pep8 freeze.py
 - pyflakes app.py
 - pep8 freeze.py
